# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Schedule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, user_id=None, title=None, start_time=None, end_time=None, description=None, color=None):  # noqa: E501
        """Schedule - a model defined in OpenAPI

        :param id: The id of this Schedule.  # noqa: E501
        :type id: str
        :param user_id: The user_id of this Schedule.  # noqa: E501
        :type user_id: str
        :param title: The title of this Schedule.  # noqa: E501
        :type title: str
        :param start_time: The start_time of this Schedule.  # noqa: E501
        :type start_time: datetime
        :param end_time: The end_time of this Schedule.  # noqa: E501
        :type end_time: datetime
        :param description: The description of this Schedule.  # noqa: E501
        :type description: str
        :param color: The color of this Schedule.  # noqa: E501
        :type color: str
        """
        self.openapi_types = {
            'id': str,
            'user_id': str,
            'title': str,
            'start_time': datetime,
            'end_time': datetime,
            'description': str,
            'color': str
        }

        self.attribute_map = {
            'id': 'id',
            'user_id': 'userId',
            'title': 'title',
            'start_time': 'startTime',
            'end_time': 'endTime',
            'description': 'description',
            'color': 'color'
        }

        self._id = id
        self._user_id = user_id
        self._title = title
        self._start_time = start_time
        self._end_time = end_time
        self._description = description
        self._color = color

    @classmethod
    def from_dict(cls, dikt) -> 'Schedule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Schedule of this Schedule.  # noqa: E501
        :rtype: Schedule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Schedule.


        :return: The id of this Schedule.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Schedule.


        :param id: The id of this Schedule.
        :type id: str
        """

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this Schedule.


        :return: The user_id of this Schedule.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Schedule.


        :param user_id: The user_id of this Schedule.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def title(self):
        """Gets the title of this Schedule.


        :return: The title of this Schedule.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Schedule.


        :param title: The title of this Schedule.
        :type title: str
        """

        self._title = title

    @property
    def start_time(self):
        """Gets the start_time of this Schedule.


        :return: The start_time of this Schedule.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this Schedule.


        :param start_time: The start_time of this Schedule.
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this Schedule.


        :return: The end_time of this Schedule.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this Schedule.


        :param end_time: The end_time of this Schedule.
        :type end_time: datetime
        """

        self._end_time = end_time

    @property
    def description(self):
        """Gets the description of this Schedule.


        :return: The description of this Schedule.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Schedule.


        :param description: The description of this Schedule.
        :type description: str
        """

        self._description = description

    @property
    def color(self):
        """Gets the color of this Schedule.


        :return: The color of this Schedule.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Schedule.


        :param color: The color of this Schedule.
        :type color: str
        """

        self._color = color
