# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Task(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, user_id=None, title=None, type=None, start=None, end=None, deadline=None, est=None, actual_time=None, description=None, done=None, color=None):  # noqa: E501
        """Task - a model defined in OpenAPI

        :param uuid: The uuid of this Task.  # noqa: E501
        :type uuid: str
        :param user_id: The user_id of this Task.  # noqa: E501
        :type user_id: str
        :param title: The title of this Task.  # noqa: E501
        :type title: str
        :param type: The type of this Task.  # noqa: E501
        :type type: str
        :param start: The start of this Task.  # noqa: E501
        :type start: datetime
        :param end: The end of this Task.  # noqa: E501
        :type end: datetime
        :param deadline: The deadline of this Task.  # noqa: E501
        :type deadline: datetime
        :param est: The est of this Task.  # noqa: E501
        :type est: datetime
        :param actual_time: The actual_time of this Task.  # noqa: E501
        :type actual_time: float
        :param description: The description of this Task.  # noqa: E501
        :type description: str
        :param done: The done of this Task.  # noqa: E501
        :type done: bool
        :param color: The color of this Task.  # noqa: E501
        :type color: str
        """
        self.openapi_types = {
            'uuid': str,
            'user_id': str,
            'title': str,
            'type': str,
            'start': datetime,
            'end': datetime,
            'deadline': datetime,
            'est': datetime,
            'actual_time': float,
            'description': str,
            'done': bool,
            'color': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'user_id': 'userId',
            'title': 'title',
            'type': 'type',
            'start': 'start',
            'end': 'end',
            'deadline': 'deadline',
            'est': 'est',
            'actual_time': 'actualTime',
            'description': 'description',
            'done': 'done',
            'color': 'color'
        }

        self._uuid = uuid
        self._user_id = user_id
        self._title = title
        self._type = type
        self._start = start
        self._end = end
        self._deadline = deadline
        self._est = est
        self._actual_time = actual_time
        self._description = description
        self._done = done
        self._color = color

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        """Gets the uuid of this Task.


        :return: The uuid of this Task.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Task.


        :param uuid: The uuid of this Task.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def user_id(self):
        """Gets the user_id of this Task.


        :return: The user_id of this Task.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Task.


        :param user_id: The user_id of this Task.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def title(self):
        """Gets the title of this Task.


        :return: The title of this Task.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Task.


        :param title: The title of this Task.
        :type title: str
        """

        self._title = title

    @property
    def type(self):
        """Gets the type of this Task.


        :return: The type of this Task.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Task.


        :param type: The type of this Task.
        :type type: str
        """
        allowed_values = ["startend", "deadline"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def start(self):
        """Gets the start of this Task.


        :return: The start of this Task.
        :rtype: datetime
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this Task.


        :param start: The start of this Task.
        :type start: datetime
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this Task.


        :return: The end of this Task.
        :rtype: datetime
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this Task.


        :param end: The end of this Task.
        :type end: datetime
        """

        self._end = end

    @property
    def deadline(self):
        """Gets the deadline of this Task.


        :return: The deadline of this Task.
        :rtype: datetime
        """
        return self._deadline

    @deadline.setter
    def deadline(self, deadline):
        """Sets the deadline of this Task.


        :param deadline: The deadline of this Task.
        :type deadline: datetime
        """

        self._deadline = deadline

    @property
    def est(self):
        """Gets the est of this Task.


        :return: The est of this Task.
        :rtype: datetime
        """
        return self._est

    @est.setter
    def est(self, est):
        """Sets the est of this Task.


        :param est: The est of this Task.
        :type est: datetime
        """

        self._est = est

    @property
    def actual_time(self):
        """Gets the actual_time of this Task.


        :return: The actual_time of this Task.
        :rtype: float
        """
        return self._actual_time

    @actual_time.setter
    def actual_time(self, actual_time):
        """Sets the actual_time of this Task.


        :param actual_time: The actual_time of this Task.
        :type actual_time: float
        """

        self._actual_time = actual_time

    @property
    def description(self):
        """Gets the description of this Task.


        :return: The description of this Task.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Task.


        :param description: The description of this Task.
        :type description: str
        """

        self._description = description

    @property
    def done(self):
        """Gets the done of this Task.


        :return: The done of this Task.
        :rtype: bool
        """
        return self._done

    @done.setter
    def done(self, done):
        """Sets the done of this Task.


        :param done: The done of this Task.
        :type done: bool
        """

        self._done = done

    @property
    def color(self):
        """Gets the color of this Task.


        :return: The color of this Task.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Task.


        :param color: The color of this Task.
        :type color: str
        """

        self._color = color
